name: memo_app_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  storybook_flutter: ^0.14.0
  line_icons: ^2.0.3
  flutter_feather_icons: ^2.0.0+1
  shimmer: ^3.0.0
  http: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.2.6
  connectivity_plus: ^6.0.3
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansCJKjp-Regular.otf
        - asset: assets/fonts/NotoSansCJKjp-Bold.otf
          weight: 700

flutter_icons:       
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"