name: memo_app_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # flutter_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  storybook_flutter: ^0.14.0
  line_icons: ^2.0.3
  flutter_feather_icons: ^2.0.0+1
  shimmer: ^3.0.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansCJKjp-Regular.otf
        - asset: assets/fonts/NotoSansCJKjp-Bold.otf
          weight: 700
